export const sites = [
  {
    name: "FCA News",
    url: "https://www.fca.org.uk/news",
    selectors: {
      container: "li.content-list-item",
      title: "span.content-item__title",
      date: "time",
      summary: "",
      link: "a",
    },
  },
  {
    name: "Munich Re Media",
    url: "https://www.munichre.com/en/company/media-relations.html",
    selectors: {
      container: "div.searchResults__resultPressRelease",
      title: "div. searchResults__resultPressReleaseTitle",
      date: "div.searchResults__resultPressReleaseCategory",
      summary: "",
      link: "a.searchResults__resultPressReleaseLink",
    },
  },
  {
    name: "ABI News",
    url: "https://www.abi.org.uk/news/",
    selectors: {
      container: "li.article-page-partial-list-item",
      title: "h2 a",
      date: "p.date",
      summary: "p.summary, p.main-body",
      link: "h2 a",
    },
  },
  {
    name: "Lloyd's Press Releases",
    url: "https://www.lloyds.com/insights/media-centre/press-releases",
    selectors: {
      container: "div.individual-card",
      title: "h3",
      date: "div",
      summary: "p",
      link: "a",
    },
  },
  {
    name: "Swiss Re Sigma",
    url: "https://sigma.swissre.com/",
    selectors: {
      container: "article.node--type-publication",
      title: "h3.title",
      date: "time.datetime",
      summary: "div.field--name-body",
      link: "a[rel='bookmark']",
    },
  },
  {
    name: "SCOR Press & News",
    url: "https://www.scor.com/en/press-releases-and-news",
    selectors: {
      container: "div.node--type-news, div.node--type-press-release",
      title: "h2 a, h3 a",
      date: "time.datetime, p.field--name-node-post-date",
      summary: "",
      link: "h2 a, h3 a",
    },
  },
  {
    name: "Hannover Re News",
    url: "https://www.hannover-re.com/de/presse/unternehmensnachrichten",
    selectors: {
      container: "a.message.message--short",
      title: "h3.message__headline",
      date: "span.typography--copy:first-child",
      summary: "",
      link: "a",
    },
  },
  {
    name: "GDV Articles",
    url: "https://www.gdv.de/gdv",
    selectors: {
      container: "li.ibmix-latest-content-teaser__list-item",
      title: "h4.ibmix-latest-content-teaser__item-headline-text",
      date: "span.ibmix-latest-content-teaser__item-date",
      summary: "p.ibmix-latest-content-teaser__item-text",
      link: "a.ibmix-latest-content-teaser__list-item-link",
    },
  },
  {
    name: "Howden Re News",
    url: "https://www.howdenre.com/news-insights",
    selectors: {
      container: "article.articles-block__article",
      title: "h4.articles-block__article-title",
      date: "div.articles-block__article-date",
      summary: "",
      link: "a.articles-block__article-link",
    },
  },
  {
    name: "Bank of England News",
    url: "https://www.bankofengland.co.uk/news",
    selectors: {
      container: "a.release",
      title: "h3.grid-view",
      date: "time.release-date",
      summary: "",
      link: "a",
    },
  },
  {
    name: "Capgemini Insurance Research",
    url: "https://www.capgemini.com/be-en/insights/research-library/?industry=insurance",
    selectors: {
      container: "div.box--event",
      title: "h3.archive-blogs-subtitle",
      date: "span.box-date",
      summary: "",
      link: "a.box-title",
    },
  },
  {
    name: "Gallagher Re News & Insights",
    url: "https://www.ajg.com/gallagherre/news-and-insights/",
    selectors: {
      container: "article.ajg-news-card",
      title: "h3.ajg-standard-card-trunc",
      date: "span.ajg-date-card",
      summary: "",
      link: "a",
    },
  },
  {
    name: "Zurich News Releases",
    url: "https://www.zurich.com/media/news-releases",
    selectors: {
      container: "div.searchnews-content-card",
      title: "p.searchnews-content-card__description",
      date: "p.searchnews-content-card__title",
      summary: "",
      link: "a",
    },
  },
  {
    name: "Chubb News Releases",
    url: "https://news.chubb.com/news-releases",
    selectors: {
      container: "li.wd_item",
      title: "a",
      date: "div.wd_date",
      summary: "",
      link: "a",
    },
  },
  {
    name: "AIG Press Releases",
    url: "https://www.aig.co.uk/home/insight-page/press-releases",
    selectors: {
      container: "article",
      title: "div.nir-widget--news--headline a",
      date: "div.nir-widget--news--date-time",
      summary: "",
      link: "div.nir-widget--news--headline a",
    },
  },
  {
    name: "AIG News Releases (Global)",
    url: "https://www.aig.com/home/newsroom/news-releases",
    selectors: {
      container: "article",
      title: "div.nir-widget--news--headline a",
      date: "div.nir-widget--news--date-time",
      summary: "",
      link: "div.nir-widget--news--headline a",
    },
  },
  {
    name: "Tokio Marine Holdings News",
    url: "https://www.tokiomarinehd.com/en/newsroom/release/",
    selectors: {
      container: "li.m-list-news__item",
      title: "p.m-list-news__title",
      date: "span.m-list-news__date",
      summary: "",
      link: "a.m-list-news__inner",
    },
  },
  {
    name: "AXA Press Releases",
    url: "https://www.axa.com/press/press-releases",
    selectors: {
      container: "li.sc-djvmMF",
      title: "div.sc-hKpBwk",
      date: "div.sc-iXxrte",
      summary: "",
      link: "a.sc-jmnVvD",
    },
  },
  {
    name: "AXA XL Press Releases",
    url: "https://axaxl.com/press-releases",
    selectors: {
      container: "div.search-box.press-release",
      title: "div.search-box-heading",
      date: "div.search-box-sub",
      summary: "div.search-box-para",
      link: "a.search-view-all, a.search-view-all.press-release-results",
    },
  },
  {
    name: "MAPFRE Press Releases",
    url: "https://www.mapfre.com/en/newsroom/press-releases/",
    selectors: {
      container: "div.cardZoomCarousel",
      title: "div.cardZoomCarousel__title",
      date: "",
      summary: "div.cardZoomCarousel__subtitle",
      link: "a.cardZoomCarousel__arrowWrapper",
    },
  },
  {
    name: "BaFin Aktuelles",
    url: "https://www.bafin.de/DE/PublikationenDaten/Aktuelles/aktuelles_node.html",
    selectors: {
      container: "tr",
      title: "td a",
      date: "td.odd:first-child",
      summary: "",
      link: "td a",
    },
  },
  {
    name: "Insurance Europe News",
    url: "https://www.insuranceeurope.eu/news",
    selectors: {
      container: "div.el-objectnews",
      title: "h3 a",
      date: "div.date",
      summary: "",
      link: "h3 a",
    },
  },
  {
    name: "Geneva Association News",
    url: "https://www.genevaassociation.org/news-and-media",
    selectors: {
      container: "div.card.shadow-sm.views-row",
      title: "h3.cards-heading",
      date: "time.datetime",
      summary: "",
      link: "a.stretched-link",
    },
  },
];
